language: android
jdk: openjdk11
os: linux
sudo: false
if: branch = master OR tag IS present
android:
  licenses:
    - android-sdk-license-.+
    - google-gdk-license-.+
    - android-sdk-preview-license-.+
  components:
    - build-tools-31.0.0
    - android-31
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-24
env:
  global:
    - TARGET_VERSION=31
    - ANDROID_BUILD_TOOLS_VERSION=31.0.0
    - ANDROID_HOME=~/android-sdk
    - ADB_INSTALL_TIMEOUT=8
before_install:
  - openssl aes-256-cbc -K $encrypted_554001b6719d_key -iv $encrypted_554001b6719d_iv
    -in secure.keystore.enc -out secure.keystore -d
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip"
    -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}"
    --sdk_root=$ANDROID_HOME
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"
before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-window &
  - bash android-wait-for-emulator
  - adb shell input keyevent 82 &
  - chmod +x gradlew
script:
  - "./gradlew clean"
  - "./gradlew test"
  - "./gradlew connectedAndroidTest -PdisablePreDex"
  - "./gradlew assembleDebug assembleRelease"
after_success:
  - bash <(curl -s https://codecov.io/bash)
