[versions]
# App configurations, not dependencies
benchmarkMacroJunit4 = "1.2.2"
minSdk = "28"
targetSdk = "34"
compileSdk = "34"
buildToolsVersion = "34.0.0"

androidx-recyclerview = "1.3.2"
appcompat = "1.6.1"
commonJava8 = "1.1.1"
constraintlayout = "2.1.4"
converterMoshi = "2.9.0"
coreKtx = "1.5.0"
coreSplashscreen = "1.0.1"
coreTesting = "2.2.0"
datastoreVersion = "1.0.0"
fragmentTesting = "1.6.2"
glide = "4.16.0"
gradle = "8.1.1"
hiltAndroidGradlePlugin = "2.47"
jetbrains-kotlinxCoroutinesTest = "1.7.3"
junitJupiterApi = "5.10.1"
legacySupportV4 = "1.0.0"
lifecycleExtensions = "2.2.0"
loggingInterceptor = "5.0.0-alpha.12"
material = "1.9.0"
retrofit = "2.9.0"
moshi = "1.15.0"

androidx-activity-compose = "1.7.2"
androidx-core-ktx = "1.12.0"
androidx-lifecycle-runtime-compose = "2.6.1"
androidx-navigation-compose = "2.7.6"
coroutines = "1.7.3"
espresso = "3.5.1"
gradleplugin = "8.2.0"
hilt = "2.47"
junit = "4.13.2"
kotest = "5.6.2"
kover = "0.7.3"
ktlint = "11.5.1"
leakcanary = "2.12"
room = "2.5.2"
test-rules = "1.5.0"
test-ext = "1.1.5"
timber = "5.0.1"
kotlin = "1.9.21"
# ksp is linked to Kotlin version https://github.com/google/ksp/releases
devtoolsksp = "1.9.21-1.0.16"
uiautomator = "2.2.0"

[libraries]
adapter-rxjava2 = { module = "com.squareup.retrofit2:adapter-rxjava2", version.ref = "retrofit" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastoreVersion" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "fragmentTesting" }
androidx-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "test-ext" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle-runtime-compose" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-runtime-compose" }

androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation-compose" }
androidx-navigation-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation-compose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" } # use with ksp
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
common-java8 = { module = "android.arch.lifecycle:common-java8", version.ref = "commonJava8" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "coreKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "jetbrains-kotlinxCoroutinesTest" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-junit4 = { group = "androidx.test.ext", name = "junit", version.ref = "test-ext" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-property = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }

leakcanary-android = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }

[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtoolsksp" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidx-navigation-compose" }
